#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Setting Node Memory to 8 GB.  Usefull as the project gets bigger for cloud building"
export NODE_OPTIONS="--max-old-space-size=8192"

echo "Linting with NX "
npx nx lint

echo "StyleLint with NX"
npx nx stylelint

echo "Using NXs built in format which uses Prettier"
npx nx format

echo "Building"
npx nx build --project startup-glossary



